### ISSUE TITLE
¿Qué es una Asignatura? 

### ISSUE THREAD

**Issue by juanmaaf** [JLombar/HorariosAutomatricula#8]
De acuerdo con #5 , vemos que el alumno trata de matricularse en muchas asignaturas. Pero, ¿qué es una asignatura? Planteada esta pregunta necesitamos definir en el ámbito de este problema qué es una asignatura, teniendo en cuenta los distintos grupos.

**Comment by JJ** [comment]
> De acuerdo con #5 , vemos que el alumno trata de matricularse en muchas asignaturas. Pero, ¿qué es una asignatura? Una asignatura es una materia específica que pertenece a un plan de estudios. Debe tener en cuenta el grupo, horario, mención a la que pertenece y profesor o profesores asignados.

¡Por qué hay que tener en cuenta todo eso? ¿Qué tiene que ver la mención y los profesores asignados con que tenga que asistir a clase?

Se trata de que las HUs sirvan para contextualizar el problema, no de que cojas palabras de la misma y pongas lo que se te ocurra.

**Comment by juanmaaf** [comment]
Es verdad, estaba teniendo en cuenta demasiadas cosas cuando basta con considerar el Horario, clave del problema que tiene el usuario. Dejaré de considerar la mención, ya que los profesores ya los borré.

**Comment by juanmaaf** [comment]
Redefino el issue, ya que el horario se tiene en cuenta en el grupo de cada asignatura.
