### ISSUE TITLE
¿Cómo gestionar/conocer los conflictos entre asignaturas?

### ISSUE THREAD

**Issue by juanmaaf** [JLombar/HorariosAutomatricula#9]
Como vemos en #5 , el alumno encuentra numerosos conflictos entre las asignaturas en las que quiere matricularse. ¿Cómo sabemos esos conflictos? Debe tener en cuenta las distintas asignaturas y los horarios de las mismas.

**Comment by juanmaaf** [comment]
Ya he eliminado lo referente a este issue, indicando el close. Fue un error mío entender que era necesario modelar las entidades necesarias y calcular el problema, obteniendo los conflictos entre las distintas Asignaturas.

**Comment by juanmaaf** [comment]
Cierra este Issue  @JLombar . No es necesario en el desarrollo de este Milestone.

**Comment by JJ** [comment]
Si cerráis esto de esta forma os dará error en todos los objetivos subsiguientes. Todos los issues se cierran desde un commit.

**Comment by juanmaaf** [comment]
Ya hice antes el commit con el close

**Comment by JJ** [comment]
Pues se cerrará cuando fusiones la rama entonces. No tenéis que cerrarlo a mano *nunca*
